; ESP-NOW Remote Control Project
; Two environments: remote (TX) and base_station (RX)

[platformio]
default_envs = remote, base_station, base_station_serial
src_dir = src
lib_dir = lib

[env:remote]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_flags =
    -D REMOTE
    ; -D DEBUG    ; uncomment to enable serial debug output
build_src_filter =
    +<remote/>
lib_deps =

[env:base_station]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -D BASE_STATION
    ; -D DEBUG    ; uncomment to enable serial debug output
build_src_filter =
    +<base_station/>
lib_deps =

[env:base_station_serial]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_flags =
    -D BASE_STATION_SERIAL
build_src_filter =
    +<base_station_serial/>
lib_deps =
